### PR TITLE
Fix #1 by changing default user-search limit.

### LINKED ISSUE #1: Cannot successfully share Calendar with Everyone-Group 0.1.0 in NC 14/15/16
Thanks for the plugin. Needed functionality.
In NC 14.0.0 with plugin version 0.1.0 I cannot share a Calender with the everyone-group (files/folders do work). The log has this entry which I believe is connected:

```
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing
'SELECT `uid`, `displayname` FROM `oc_users` `u`
  LEFT JOIN `oc_preferences` `p` ON (`userid` = `uid`)
    AND (`appid` = 'settings') AND (`configkey` = 'email')
  WHERE (`uid` COLLATE UTF8_general_ci LIKE ?) OR (`displayname` COLLATE UTF8_general_ci LIKE ?) OR (`configvalue` COLLATE UTF8_general_ci LIKE ?)
  ORDER BY `uid_lower` ASC LIMIT -1 OFFSET 0' with params ["%%", "%%", "%%"]: 

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; 
check the manual that corresponds to your MariaDB server version for the right syntax to use
near '-1 OFFSET 0' at line 1
```
(new-lines and some spaces inserted for readability)

Most users are authenticated via LDAP in my setup.
In the calendar-app, the everyone-group autocompletes and is selectable, but afterwards the entry does not show up in the list of share-receivers (under the calendar name).

### PR DESCRIPTION
**Pull request by fwolfst**
`/lib/private/User/Manager.php` implements `IUserManager#search` with
a default limit of null.  I assume that the value gets passed on to
query the SQL-Server, where a -1 is a invalid value at least for
the mysql-Version I use (see below).  A default value of null does lead
to the proper behaviour in my case.

According to e.g. MySQL doc, LIMIT should be a nonnegative integer,
reference: https://dev.mysql.com/doc/refman/8.0/en/select.html .

It fixes the issue for me, tested only with

$ mysql --version
mysql  Ver 15.1 Distrib 10.0.36-MariaDB [....]

from Ubuntu packages.

Sorry for the mess with the first PR.

### CODE REVIEW

**Comment by filisko** [comment]
what do you think @icewind1991 ? 😄

**Comment by icewind1991** [comment]
apologies. for taking so long to look into this.

`-1` should remain the default for the function signatures as that is the signature of the implemented interface, but the default `-1` should be changed into a `null` when passing it to the search

**Comment by fwolfst** [comment]
Mmh, `IUserManager` does this differently (https://github.com/nextcloud/server/blob/c5c219206107bfa8f84feb9bfc2429582183de69/lib/public/IUserManager.php#L117) and imho correctly/better than `IGroupManager`.
I see real world exceptions without my patch, so to me it seems that at some point the `-1` is not changed into a `null`.

**Comment by fwolfst** [comment]
> Mmh, `IUserManager` does this differently (https://github.com/nextcloud/server/blob/c5c219206107bfa8f84feb9bfc2429582183de69/lib/public/IUserManager.php#L117) and imho correctly/better than `IGroupManager`.
> I see real world exceptions without my patch, so to me it seems that at some point the `-1` is not changed into a `null`.

**Comment by fwolfst** [comment]
Maybe I read you wrong and too quick: Are you proposing that I re-rwrite my patch, such that it checks for `-1`iness of `$limit` and pass it on correctly to `->userManager`?

Out of my head without knowing PHP ternaries, something like `search(..., ($limit < 0) ? null : $limit, ....)`? Or, more verbose with an `if/else`? I really don't know php conventions.

I can gladly provide that patch.

**Comment by fwolfst** [comment]
Anyway, `-1` in the interface signature seems like a bad idea. On the other hand, the recipient has to check for negative values anyway (which apparently not all `IUserManager` implementations do, I use mixed LDAP and local backend btw). You are far more involved in nextcloud development. What do you think, is it worth filing an issue against nextcloud/server (for the interface signature)? And/or against the 'UserManager` that does not check for positivity of the `$limit` parameter?

**Comment by icewind1991** [comment]
Changing the default value in the signature (either just here or also in core) would run into issues with places that use call the method and assume they can pass `-1` to get the default behaviour of no limit.

`-1` is probably not the best default, and having  different one for `usersInGroup` and `UserManager::search` isn't great, but changing it now is not worth the effort imo

**Comment by fwolfst** [comment]
> Changing the default value in the signature (either just here or also in core) would run into issues with places that use call the method and assume they can pass `-1` to get the default behaviour of no limit.

From my understandig - as long as the implementations check for negativity and null and treat this as UNLIMITED - this wouldnt be the case, but your call.

**Comment by tikoflano** [comment]
Any news regarding this? Do you need any help?

**Comment by fwolfst** [comment]
@tikoflano me? No. I was thinking lately to redo the PR in the way outlined. What I need is an answer from @icewind1991 . But good people are busy, sometimes :)

> Out of my head without knowing PHP ternaries, something like search(..., ($limit < 0) ? null : $limit, ....)? Or, more verbose with an if/else? I really don't know php conventions.

I dont want to "waste" much time in producing php code that does not meet the standards, but yes, maybe I should just give it another try.

**Comment by fwolfst** [comment]
@tikoflano I updated the code; Now, ping @icewind1991

**Comment by fwolfst** [comment]
@icewind1991 I manually patch after each update. Any chances to get this merged in?

**Comment by icewind1991** [comment]
Thanks for the work @fwolfst

**Pull request merged**
